// AUTO-GENERATED by `scripts/gen-themes.ts`. DO NOT EDIT.
// Re-run `bun scripts/gen-themes.ts` after adding/renaming a theme.

import type { LoaderMap } from "@zaly/shared"
import type { Theme } from "./types.ts"

/**
 * Async loader map for every built-in theme. Each entry returns the
 * raw JSON; `themes/index.ts` wraps these with `resolveTheme` to
 * produce a fully-resolved `Theme` from the registry. Bundlers
 * code-split each `import("…json")` into its own chunk, so apps only
 * pull the theme they actually load.
 *
 * `as const satisfies LoaderMap<…>` keeps the keys narrow (so
 * `BuiltinThemeName` is a literal union) but lets the value type
 * widen to `Partial<Theme>` — themes have no per-key narrow types
 * worth preserving, and the satisfies clause means `themes/index.ts`
 * can pass this map straight to `themeRegistry` with no cast.
 */
export const builtin = {
  "catppuccin-latte": () =>
    import("../../assets/themes/catppuccin-latte.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  "catppuccin-mocha": () =>
    import("../../assets/themes/catppuccin-mocha.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  dracula: () =>
    import("../../assets/themes/dracula.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  "github-dark": () =>
    import("../../assets/themes/github-dark.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  "github-light": () =>
    import("../../assets/themes/github-light.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  "gruvbox-dark-medium": () =>
    import("../../assets/themes/gruvbox-dark-medium.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  nord: () =>
    import("../../assets/themes/nord.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  "one-dark-pro": () =>
    import("../../assets/themes/one-dark-pro.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  "rose-pine": () =>
    import("../../assets/themes/rose-pine.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  "tokyonight-day": () =>
    import("../../assets/themes/tokyonight-day.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  "tokyonight-moon": () =>
    import("../../assets/themes/tokyonight-moon.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  "tokyonight-night": () =>
    import("../../assets/themes/tokyonight-night.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
  "tokyonight-storm": () =>
    import("../../assets/themes/tokyonight-storm.json", { with: { type: "json" } }).then(
      (m) => m.default as Partial<Theme>
    ),
} as const satisfies LoaderMap<Promise<Partial<Theme>>>

export type BuiltinThemeName = keyof typeof builtin
