// AUTO-GENERATED by `scripts/gen-themes.ts`. DO NOT EDIT.
// Re-run `bun scripts/gen-themes.ts` after adding/renaming a theme.

import raw from "../../assets/themes/catppuccin-mocha.json" with { type: "json" }
import { resolveTheme } from "../style/theme.ts"

const catppuccinMocha = resolveTheme(raw)

export default catppuccinMocha
export { catppuccinMocha }
