// AUTO-GENERATED by `scripts/gen-themes.ts`. DO NOT EDIT.
// Re-run `bun scripts/gen-themes.ts` after adding/renaming a theme.

import raw from "../../assets/themes/dracula.json" with { type: "json" }
import { resolveTheme } from "../style/theme.ts"

const dracula = resolveTheme(raw)

export default dracula
export { dracula }
