// AUTO-GENERATED by `scripts/gen-themes.ts`. DO NOT EDIT.
// Re-run `bun scripts/gen-themes.ts` after adding/renaming a theme.

import raw from "../../assets/themes/github-dark.json" with { type: "json" }
import { resolveTheme } from "../style/theme.ts"

const githubDark = resolveTheme(raw)

export default githubDark
export { githubDark }
