// AUTO-GENERATED by `scripts/gen-themes.ts`. DO NOT EDIT.
// Re-run `bun scripts/gen-themes.ts` after adding/renaming a theme.

import raw from "../../assets/themes/gruvbox-dark-medium.json" with { type: "json" }
import { resolveTheme } from "../style/theme.ts"

const gruvboxDarkMedium = resolveTheme(raw)

export default gruvboxDarkMedium
export { gruvboxDarkMedium }
