// AUTO-GENERATED by `scripts/gen-themes.ts`. DO NOT EDIT.
// Re-run `bun scripts/gen-themes.ts` after adding/renaming a theme.

import type { Theme } from "../style/theme.ts"

/**
 * Async loader map for every built-in theme. Each entry code-splits
 * into its own chunk, so picking a theme at runtime by user-config
 * string doesn't pull every bundled theme into the main chunk.
 *
 * ```ts
 * import { themes } from "@zaly/tui/themes"
 * const theme = await themes[argv.theme ?? "tokyonight-moon"]()
 * ```
 *
 * For static, tree-shaken imports of a known theme, use the per-theme
 * subpath instead:
 *
 * ```ts
 * import dracula from "@zaly/tui/themes/dracula"
 * ```
 */
export const themes = {
  "catppuccin-latte": () => import("./catppuccin-latte.ts").then((m) => m.default),
  "catppuccin-mocha": () => import("./catppuccin-mocha.ts").then((m) => m.default),
  "dracula": () => import("./dracula.ts").then((m) => m.default),
  "github-dark": () => import("./github-dark.ts").then((m) => m.default),
  "github-light": () => import("./github-light.ts").then((m) => m.default),
  "gruvbox-dark-medium": () => import("./gruvbox-dark-medium.ts").then((m) => m.default),
  "nord": () => import("./nord.ts").then((m) => m.default),
  "one-dark-pro": () => import("./one-dark-pro.ts").then((m) => m.default),
  "rose-pine": () => import("./rose-pine.ts").then((m) => m.default),
  "tokyonight-day": () => import("./tokyonight-day.ts").then((m) => m.default),
  "tokyonight-moon": () => import("./tokyonight-moon.ts").then((m) => m.default),
  "tokyonight-night": () => import("./tokyonight-night.ts").then((m) => m.default),
  "tokyonight-storm": () => import("./tokyonight-storm.ts").then((m) => m.default),
} as const satisfies Record<string, () => Promise<Theme>>

/** Union of every built-in theme name. */
export type ThemeName = keyof typeof themes
