// AUTO-GENERATED by `scripts/gen-themes.ts`. DO NOT EDIT.
// Re-run `bun scripts/gen-themes.ts` after adding/renaming a theme.

import raw from "../../assets/themes/one-dark-pro.json" with { type: "json" }
import { resolveTheme } from "../style/theme.ts"

const oneDarkPro = resolveTheme(raw)

export default oneDarkPro
export { oneDarkPro }
