// AUTO-GENERATED by `scripts/gen-themes.ts`. DO NOT EDIT.
// Re-run `bun scripts/gen-themes.ts` after adding/renaming a theme.

import raw from "../../assets/themes/rose-pine.json" with { type: "json" }
import { resolveTheme } from "../style/theme.ts"

const rosePine = resolveTheme(raw)

export default rosePine
export { rosePine }
