// AUTO-GENERATED by `scripts/gen-themes.ts`. DO NOT EDIT.
// Re-run `bun scripts/gen-themes.ts` after adding/renaming a theme.

import raw from "../../assets/themes/tokyonight-night.json" with { type: "json" }
import { resolveTheme } from "../style/theme.ts"

const tokyonightNight = resolveTheme(raw)

export default tokyonightNight
export { tokyonightNight }
