// Generate `src/themes/*.ts` + `src/themes/index.ts` from the JSON
// files under `assets/themes/`. Each JSON file becomes a standalone
// subpath export so tree-shaken apps only bundle the themes they
// import; the index exposes an async loader map for CLIs that pick a
// theme by string at runtime (code-split per theme by any modern
// bundler).
//
// Idempotent — re-run after adding or renaming a JSON file.

import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import { basename, join } from "node:path"

const ASSET_DIR = "assets/themes"
const OUT_DIR = "src/themes"

const header = `// AUTO-GENERATED by \`scripts/gen-themes.ts\`. DO NOT EDIT.\n// Re-run \`bun scripts/gen-themes.ts\` after adding/renaming a theme.\n\n`

function camelCase(name: string): string {
  return name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
}

function genTheme(name: string): string {
  const camel = camelCase(name)
  return `${header}import raw from "../../${ASSET_DIR}/${name}.json" with { type: "json" }
import { resolveTheme } from "../style/theme.ts"

const ${camel} = resolveTheme(raw)

export default ${camel}
export { ${camel} }
`
}

function genIndex(names: readonly string[]): string {
  const entries = names
    .map((n) => `  "${n}": () => import("./${n}.ts").then((m) => m.default),`)
    .join("\n")

  return `${header}import type { Theme } from "../style/theme.ts"

/**
 * Async loader map for every built-in theme. Each entry code-splits
 * into its own chunk, so picking a theme at runtime by user-config
 * string doesn't pull every bundled theme into the main chunk.
 *
 * \`\`\`ts
 * import { themes } from "@zaly/tui/themes"
 * const theme = await themes[argv.theme ?? "tokyonight-moon"]()
 * \`\`\`
 *
 * For static, tree-shaken imports of a known theme, use the per-theme
 * subpath instead:
 *
 * \`\`\`ts
 * import dracula from "@zaly/tui/themes/dracula"
 * \`\`\`
 */
export const themes = {
${entries}
} as const satisfies Record<string, () => Promise<Theme>>

/** Union of every built-in theme name. */
export type ThemeName = keyof typeof themes
`
}

function main(): void {
  const names = readdirSync(ASSET_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => basename(f, ".json"))
    .toSorted()

  // Wipe the dir to clean out renamed / deleted themes, then recreate.
  rmSync(OUT_DIR, { force: true, recursive: true })
  mkdirSync(OUT_DIR, { recursive: true })

  for (const name of names) {
    writeFileSync(join(OUT_DIR, `${name}.ts`), genTheme(name))
  }
  writeFileSync(join(OUT_DIR, "index.ts"), genIndex(names))

  console.log(`✔  wrote ${names.length} themes + index to ${OUT_DIR}/`)
}

main()
